CREATE TABLE public.fuel_card_accounts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES public.tenants(id), country_id uuid NOT NULL REFERENCES public.tenant_countries(id), client_id uuid NOT NULL REFERENCES public.clients(id), kind text NOT NULL CHECK(kind IN ('prepaid','postpaid')), contract_reference text, credit_limit numeric(16,2) NOT NULL DEFAULT 0 CHECK(credit_limit>=0), prepaid_balance numeric(16,2) NOT NULL DEFAULT 0 CHECK(prepaid_balance>=0), credit_used numeric(16,2) NOT NULL DEFAULT 0 CHECK(credit_used>=0), status text NOT NULL DEFAULT 'active' CHECK(status IN ('active','blocked','expired')), created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(id,tenant_id,country_id));
GRANT SELECT ON public.fuel_card_accounts TO authenticated; GRANT ALL ON public.fuel_card_accounts TO service_role;
ALTER TABLE public.fuel_card_accounts ENABLE ROW LEVEL SECURITY;
CREATE POLICY fuel_accounts_read ON public.fuel_card_accounts FOR SELECT TO authenticated USING(public.can_access_tenant_country(auth.uid(),tenant_id,country_id) AND public.is_module_enabled(tenant_id,country_id,'cartes_carburant') AND (public.has_permission(auth.uid(),'fuel_cards.view') OR public.is_platform_admin(auth.uid())));
CREATE TABLE public.fuel_card_vehicles (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, country_id uuid NOT NULL, account_id uuid NOT NULL, plate text NOT NULL, description text, active boolean NOT NULL DEFAULT true, UNIQUE(id,tenant_id,country_id), FOREIGN KEY(account_id,tenant_id,country_id) REFERENCES public.fuel_card_accounts(id,tenant_id,country_id));
GRANT SELECT ON public.fuel_card_vehicles TO authenticated; GRANT ALL ON public.fuel_card_vehicles TO service_role;
ALTER TABLE public.fuel_card_vehicles ENABLE ROW LEVEL SECURITY;
CREATE POLICY fuel_vehicles_read ON public.fuel_card_vehicles FOR SELECT TO authenticated USING(public.can_access_tenant_country(auth.uid(),tenant_id,country_id) AND public.is_module_enabled(tenant_id,country_id,'cartes_carburant') AND (public.has_permission(auth.uid(),'fuel_cards.view') OR public.is_platform_admin(auth.uid())));
CREATE TABLE public.fuel_card_drivers (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, country_id uuid NOT NULL, account_id uuid NOT NULL, name text NOT NULL, phone text, active boolean NOT NULL DEFAULT true, UNIQUE(id,tenant_id,country_id), FOREIGN KEY(account_id,tenant_id,country_id) REFERENCES public.fuel_card_accounts(id,tenant_id,country_id));
GRANT SELECT ON public.fuel_card_drivers TO authenticated; GRANT ALL ON public.fuel_card_drivers TO service_role;
ALTER TABLE public.fuel_card_drivers ENABLE ROW LEVEL SECURITY;
CREATE POLICY fuel_drivers_read ON public.fuel_card_drivers FOR SELECT TO authenticated USING(public.can_access_tenant_country(auth.uid(),tenant_id,country_id) AND public.is_module_enabled(tenant_id,country_id,'cartes_carburant') AND (public.has_permission(auth.uid(),'fuel_cards.view') OR public.is_platform_admin(auth.uid())));
CREATE TABLE public.fuel_cards (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, country_id uuid NOT NULL, account_id uuid NOT NULL, card_number text NOT NULL, holder_name text, vehicle_id uuid, driver_id uuid, status text NOT NULL DEFAULT 'active' CHECK(status IN ('active','blocked','replaced','expired')), expires_on date NOT NULL, replaced_by uuid, allocated_limit numeric(16,2) NOT NULL DEFAULT 0 CHECK(allocated_limit>=0), remaining numeric(16,2) NOT NULL DEFAULT 0 CHECK(remaining>=0), restrictions jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tenant_id,country_id,card_number), UNIQUE(id,tenant_id,country_id), FOREIGN KEY(account_id,tenant_id,country_id) REFERENCES public.fuel_card_accounts(id,tenant_id,country_id), FOREIGN KEY(vehicle_id,tenant_id,country_id) REFERENCES public.fuel_card_vehicles(id,tenant_id,country_id), FOREIGN KEY(driver_id,tenant_id,country_id) REFERENCES public.fuel_card_drivers(id,tenant_id,country_id));
GRANT SELECT ON public.fuel_cards TO authenticated; GRANT ALL ON public.fuel_cards TO service_role;
ALTER TABLE public.fuel_cards ENABLE ROW LEVEL SECURITY;
CREATE POLICY fuel_cards_read ON public.fuel_cards FOR SELECT TO authenticated USING(public.can_access_tenant_country(auth.uid(),tenant_id,country_id) AND public.is_module_enabled(tenant_id,country_id,'cartes_carburant') AND (public.has_permission(auth.uid(),'fuel_cards.view') OR public.is_platform_admin(auth.uid())));
CREATE TABLE public.fuel_card_transactions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, country_id uuid NOT NULL, account_id uuid NOT NULL, card_id uuid, station_id uuid, product_id uuid, vehicle_id uuid, driver_id uuid, kind text NOT NULL CHECK(kind IN ('topup','allocation','allocation_return','purchase','invoice','payment','credit_reset')), amount numeric(16,2) NOT NULL CHECK(amount>0), litres numeric(16,3), reference text, note text, occurred_at timestamptz NOT NULL DEFAULT now(), actor_id uuid NOT NULL, FOREIGN KEY(account_id,tenant_id,country_id) REFERENCES public.fuel_card_accounts(id,tenant_id,country_id), FOREIGN KEY(card_id,tenant_id,country_id) REFERENCES public.fuel_cards(id,tenant_id,country_id), FOREIGN KEY(station_id) REFERENCES public.stations(id), FOREIGN KEY(product_id) REFERENCES public.petroleum_products(id));
GRANT SELECT ON public.fuel_card_transactions TO authenticated; GRANT ALL ON public.fuel_card_transactions TO service_role;
ALTER TABLE public.fuel_card_transactions ENABLE ROW LEVEL SECURITY;
CREATE POLICY fuel_transactions_read ON public.fuel_card_transactions FOR SELECT TO authenticated USING(public.can_access_tenant_country(auth.uid(),tenant_id,country_id) AND public.is_module_enabled(tenant_id,country_id,'cartes_carburant') AND (public.has_permission(auth.uid(),'fuel_cards.view') OR public.is_platform_admin(auth.uid())));
CREATE UNIQUE INDEX fuel_transactions_reference_once ON public.fuel_card_transactions(tenant_id,country_id,reference) WHERE kind='purchase' AND reference IS NOT NULL;
CREATE TABLE public.fuel_card_limit_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, country_id uuid NOT NULL, account_id uuid NOT NULL, card_id uuid, old_limit numeric(16,2) NOT NULL, new_limit numeric(16,2) NOT NULL, reason text NOT NULL, actor_id uuid NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), FOREIGN KEY(account_id,tenant_id,country_id) REFERENCES public.fuel_card_accounts(id,tenant_id,country_id), FOREIGN KEY(card_id,tenant_id,country_id) REFERENCES public.fuel_cards(id,tenant_id,country_id));
GRANT SELECT ON public.fuel_card_limit_events TO authenticated; GRANT ALL ON public.fuel_card_limit_events TO service_role;
ALTER TABLE public.fuel_card_limit_events ENABLE ROW LEVEL SECURITY;
CREATE POLICY fuel_limits_read ON public.fuel_card_limit_events FOR SELECT TO authenticated USING(public.can_access_tenant_country(auth.uid(),tenant_id,country_id) AND public.is_module_enabled(tenant_id,country_id,'cartes_carburant') AND (public.has_permission(auth.uid(),'fuel_cards.view') OR public.is_platform_admin(auth.uid())));
CREATE TABLE public.fuel_card_invoices (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, country_id uuid NOT NULL, account_id uuid NOT NULL, period_start date NOT NULL, period_end date NOT NULL, number text NOT NULL, amount numeric(16,2) NOT NULL CHECK(amount>0), paid numeric(16,2) NOT NULL DEFAULT 0 CHECK(paid>=0), created_at timestamptz NOT NULL DEFAULT now(), actor_id uuid NOT NULL, UNIQUE(tenant_id,country_id,number), FOREIGN KEY(account_id,tenant_id,country_id) REFERENCES public.fuel_card_accounts(id,tenant_id,country_id));
GRANT SELECT ON public.fuel_card_invoices TO authenticated; GRANT ALL ON public.fuel_card_invoices TO service_role;
ALTER TABLE public.fuel_card_invoices ENABLE ROW LEVEL SECURITY;
CREATE POLICY fuel_invoices_read ON public.fuel_card_invoices FOR SELECT TO authenticated USING(public.can_access_tenant_country(auth.uid(),tenant_id,country_id) AND public.is_module_enabled(tenant_id,country_id,'cartes_carburant') AND (public.has_permission(auth.uid(),'fuel_cards.view') OR public.is_platform_admin(auth.uid())));
CREATE TABLE public.fuel_card_alerts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, country_id uuid NOT NULL, account_id uuid NOT NULL, card_id uuid, transaction_id uuid, rule_code text NOT NULL, explanation text NOT NULL, severity text NOT NULL DEFAULT 'warning', created_at timestamptz NOT NULL DEFAULT now(), FOREIGN KEY(account_id,tenant_id,country_id) REFERENCES public.fuel_card_accounts(id,tenant_id,country_id), FOREIGN KEY(card_id,tenant_id,country_id) REFERENCES public.fuel_cards(id,tenant_id,country_id));
GRANT SELECT ON public.fuel_card_alerts TO authenticated; GRANT ALL ON public.fuel_card_alerts TO service_role;
ALTER TABLE public.fuel_card_alerts ENABLE ROW LEVEL SECURITY;
CREATE POLICY fuel_alerts_read ON public.fuel_card_alerts FOR SELECT TO authenticated USING(public.can_access_tenant_country(auth.uid(),tenant_id,country_id) AND public.is_module_enabled(tenant_id,country_id,'cartes_carburant') AND (public.has_permission(auth.uid(),'fuel_cards.view') OR public.is_platform_admin(auth.uid())));
CREATE FUNCTION public.fuel_card_action(_action text,_tenant uuid,_country uuid,_account uuid DEFAULT NULL,_card uuid DEFAULT NULL,_data jsonb DEFAULT '{}'::jsonb) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE a public.fuel_card_accounts%ROWTYPE; c public.fuel_cards%ROWTYPE; v public.fuel_card_vehicles%ROWTYPE; d public.fuel_card_drivers%ROWTYPE; sid uuid; pid uuid; vid uuid; did uuid; x numeric; n numeric; res uuid; j jsonb; ref text; day_total numeric; week_total numeric; month_total numeric; outstanding numeric; inv public.fuel_card_invoices%ROWTYPE; oldval numeric; allowed text; step integer;
BEGIN
IF auth.uid() IS NULL OR NOT public.can_access_tenant_country(auth.uid(),_tenant,_country) OR NOT public.is_module_enabled(_tenant,_country,'cartes_carburant') OR NOT public.tenant_write_allowed(_tenant) THEN RAISE EXCEPTION 'Accès refusé'; END IF;
IF _action IN ('purchase') THEN allowed:='fuel_cards.create'; ELSIF _action IN ('invoice','invoice_payment') THEN allowed:='fuel_cards.validate'; ELSE allowed:='fuel_cards.edit'; END IF;
IF NOT (public.has_permission(auth.uid(),allowed) OR public.is_platform_admin(auth.uid())) THEN RAISE EXCEPTION 'Permission manquante: %',allowed; END IF;
IF _account IS NOT NULL THEN SELECT * INTO a FROM public.fuel_card_accounts WHERE id=_account AND tenant_id=_tenant AND country_id=_country FOR UPDATE; IF NOT FOUND THEN RAISE EXCEPTION 'Compte introuvable'; END IF; END IF;
IF _card IS NOT NULL THEN SELECT * INTO c FROM public.fuel_cards WHERE id=_card AND tenant_id=_tenant AND country_id=_country FOR UPDATE; IF NOT FOUND OR c.account_id IS DISTINCT FROM _account THEN RAISE EXCEPTION 'Carte hors compte'; END IF; END IF;
IF _action='account' THEN
 IF NOT (public.has_permission(auth.uid(),'fuel_cards.create') OR public.is_platform_admin(auth.uid())) THEN RAISE EXCEPTION 'Permission manquante'; END IF;
 IF NOT EXISTS(SELECT 1 FROM public.clients WHERE id=(_data->>'client_id')::uuid AND tenant_id=_tenant AND country_id=_country AND is_active) THEN RAISE EXCEPTION 'Client hors périmètre ou inactif'; END IF;
 IF _data->>'kind' NOT IN ('prepaid','postpaid') THEN RAISE EXCEPTION 'Type invalide'; END IF;
 x:=COALESCE((_data->>'limit')::numeric,0); IF x<0 THEN RAISE EXCEPTION 'Plafond négatif'; END IF;
 IF _data->>'kind'='postpaid' AND (x<=0 OR NULLIF(trim(_data->>'contract_reference'),'') IS NULL) THEN RAISE EXCEPTION 'Plafond et référence de contrat requis'; END IF;
 INSERT INTO public.fuel_card_accounts(tenant_id,country_id,client_id,kind,credit_limit,contract_reference) VALUES(_tenant,_country,(_data->>'client_id')::uuid,_data->>'kind',x,_data->>'contract_reference') RETURNING id INTO res;
ELSIF _action='vehicle' OR _action='driver' THEN
 IF _action='vehicle' THEN IF nullif(trim(_data->>'plate'),'') IS NULL THEN RAISE EXCEPTION 'Immatriculation requise'; END IF; INSERT INTO public.fuel_card_vehicles(tenant_id,country_id,account_id,plate,description) VALUES(_tenant,_country,_account,trim(_data->>'plate'),_data->>'description') RETURNING id INTO res;
 ELSE IF nullif(trim(_data->>'name'),'') IS NULL THEN RAISE EXCEPTION 'Nom requis'; END IF; INSERT INTO public.fuel_card_drivers(tenant_id,country_id,account_id,name,phone) VALUES(_tenant,_country,_account,trim(_data->>'name'),_data->>'phone') RETURNING id INTO res; END IF;
ELSIF _action='card' THEN
 IF a.status<>'active' THEN RAISE EXCEPTION 'Compte bloqué'; END IF;
 IF nullif(trim(_data->>'number'),'') IS NULL OR (_data->>'expires_on')::date<=current_date THEN RAISE EXCEPTION 'Numéro ou expiration invalide'; END IF;
 vid:=NULLIF(_data->>'vehicle_id','')::uuid; did:=NULLIF(_data->>'driver_id','')::uuid;
 IF vid IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public.fuel_card_vehicles WHERE id=vid AND account_id=_account AND active) THEN RAISE EXCEPTION 'Véhicule invalide'; END IF;
 IF did IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public.fuel_card_drivers WHERE id=did AND account_id=_account AND active) THEN RAISE EXCEPTION 'Conducteur invalide'; END IF;
 INSERT INTO public.fuel_cards(tenant_id,country_id,account_id,card_number,holder_name,expires_on,vehicle_id,driver_id,restrictions) VALUES(_tenant,_country,_account,trim(_data->>'number'),_data->>'holder',(_data->>'expires_on')::date,vid,did,COALESCE(_data->'restrictions','{}'::jsonb)) RETURNING id INTO res;
ELSIF _action='status' THEN
 IF _data->>'status' NOT IN ('active','blocked') OR c.status IN ('replaced','expired') OR (_data->>'status'='active' AND c.expires_on<current_date) THEN RAISE EXCEPTION 'Transition interdite'; END IF;
 UPDATE public.fuel_cards SET status=_data->>'status' WHERE id=c.id; res:=c.id;
ELSIF _action='replace' THEN
 IF c.status IN ('replaced','expired') OR c.expires_on<current_date OR nullif(trim(_data->>'number'),'') IS NULL OR (_data->>'expires_on')::date<=current_date THEN RAISE EXCEPTION 'Remplacement invalide'; END IF;
 INSERT INTO public.fuel_cards(tenant_id,country_id,account_id,card_number,holder_name,expires_on,vehicle_id,driver_id,restrictions,allocated_limit,remaining) VALUES(_tenant,_country,_account,trim(_data->>'number'),c.holder_name,(_data->>'expires_on')::date,c.vehicle_id,c.driver_id,c.restrictions,c.allocated_limit,c.remaining) RETURNING id INTO res;
 UPDATE public.fuel_cards SET status='replaced',remaining=0,replaced_by=res WHERE id=c.id;
ELSIF _action='topup' OR _action='allocate' OR _action='return' OR _action='limit' OR _action='reset' THEN
 x:=(_data->>'amount')::numeric; IF x IS NULL OR x<=0 THEN RAISE EXCEPTION 'Montant positif requis'; END IF;
 IF _action='topup' THEN IF a.kind<>'prepaid' THEN RAISE EXCEPTION 'Réservé au prépayé'; END IF; UPDATE public.fuel_card_accounts SET prepaid_balance=prepaid_balance+x WHERE id=a.id;
 ELSIF _action='limit' THEN IF a.kind<>'postpaid' OR nullif(trim(_data->>'reason'),'') IS NULL OR x<a.credit_used THEN RAISE EXCEPTION 'Plafond ou motif invalide'; END IF;
 oldval:=a.credit_limit; UPDATE public.fuel_card_accounts SET credit_limit=x WHERE id=a.id; INSERT INTO public.fuel_card_limit_events(tenant_id,country_id,account_id,old_limit,new_limit,reason,actor_id) VALUES(_tenant,_country,a.id,oldval,x,_data->>'reason',auth.uid());
 ELSIF _action='reset' THEN IF a.kind<>'postpaid' OR nullif(trim(_data->>'reason'),'') IS NULL OR x>a.credit_used THEN RAISE EXCEPTION 'Reconstitution invalide'; END IF; UPDATE public.fuel_card_accounts SET credit_used=credit_used-x WHERE id=a.id; INSERT INTO public.fuel_card_limit_events(tenant_id,country_id,account_id,old_limit,new_limit,reason,actor_id) VALUES(_tenant,_country,a.id,a.credit_limit-a.credit_used,a.credit_limit-a.credit_used+x,_data->>'reason',auth.uid());
 ELSE IF c.status<>'active' OR c.expires_on<current_date THEN RAISE EXCEPTION 'Carte inactive'; END IF;
 IF _action='allocate' THEN SELECT COALESCE(sum(remaining),0) INTO n FROM public.fuel_cards WHERE account_id=a.id; IF x> (CASE WHEN a.kind='prepaid' THEN a.prepaid_balance ELSE a.credit_limit-a.credit_used END)-n THEN RAISE EXCEPTION 'Réserve principale insuffisante'; END IF; UPDATE public.fuel_cards SET allocated_limit=allocated_limit+x,remaining=remaining+x WHERE id=c.id; INSERT INTO public.fuel_card_limit_events(tenant_id,country_id,account_id,card_id,old_limit,new_limit,reason,actor_id) VALUES(_tenant,_country,a.id,c.id,c.allocated_limit,c.allocated_limit+x,COALESCE(NULLIF(_data->>'reason',''),'Allocation'),auth.uid());
 ELSE IF x>c.remaining THEN RAISE EXCEPTION 'Solde carte insuffisant'; END IF; UPDATE public.fuel_cards SET allocated_limit=allocated_limit-x,remaining=remaining-x WHERE id=c.id; INSERT INTO public.fuel_card_limit_events(tenant_id,country_id,account_id,card_id,old_limit,new_limit,reason,actor_id) VALUES(_tenant,_country,a.id,c.id,c.allocated_limit,c.allocated_limit-x,COALESCE(NULLIF(_data->>'reason',''),'Restitution'),auth.uid()); END IF;
 END IF;
 IF _action IN ('topup','allocate','return','reset') THEN INSERT INTO public.fuel_card_transactions(tenant_id,country_id,account_id,card_id,kind,amount,note,actor_id) VALUES(_tenant,_country,a.id,_card,CASE _action WHEN 'return' THEN 'allocation_return' WHEN 'reset' THEN 'credit_reset' ELSE CASE WHEN _action='allocate' THEN 'allocation' ELSE 'topup' END END,x,_data->>'reason',auth.uid()) RETURNING id INTO res; END IF;
ELSIF _action='restrictions' THEN
 IF c.status='replaced' OR jsonb_typeof(_data->'restrictions') IS DISTINCT FROM 'object' THEN RAISE EXCEPTION 'Restrictions invalides'; END IF;
 j:=_data->'restrictions';
 FOREACH allowed IN ARRAY ARRAY['max_transaction','max_litres','daily_amount','weekly_amount','monthly_amount','daily_litres','weekly_litres','monthly_litres','start_hour','end_hour'] LOOP
 IF j ? allowed THEN IF (j->>allowed)::numeric<0 THEN RAISE EXCEPTION 'Restriction négative'; END IF; END IF;
 END LOOP;
 IF (j ? 'start_hour' AND (j->>'start_hour')::int>23) OR (j ? 'end_hour' AND (j->>'end_hour')::int>23) THEN RAISE EXCEPTION 'Heure invalide'; END IF;
 FOREACH allowed IN ARRAY ARRAY['products','stations','vehicles'] LOOP IF j ? allowed AND jsonb_typeof(j->allowed)<>'array' THEN RAISE EXCEPTION 'Liste de restriction invalide'; END IF; END LOOP;
 IF EXISTS(SELECT 1 FROM jsonb_array_elements_text(COALESCE(j->'products','[]'::jsonb)) q WHERE NOT EXISTS(SELECT 1 FROM public.petroleum_products p WHERE p.id=q.value::uuid AND p.tenant_id=_tenant AND p.country_id=_country)) OR EXISTS(SELECT 1 FROM jsonb_array_elements_text(COALESCE(j->'stations','[]'::jsonb)) q WHERE NOT EXISTS(SELECT 1 FROM public.stations s WHERE s.id=q.value::uuid AND s.tenant_id=_tenant AND s.country_id=_country)) OR EXISTS(SELECT 1 FROM jsonb_array_elements_text(COALESCE(j->'vehicles','[]'::jsonb)) q WHERE NOT EXISTS(SELECT 1 FROM public.fuel_card_vehicles v WHERE v.id=q.value::uuid AND v.account_id=a.id)) THEN RAISE EXCEPTION 'Restriction hors périmètre'; END IF;
 UPDATE public.fuel_cards SET restrictions=j WHERE id=c.id; res:=c.id;
ELSIF _action='purchase' THEN
 IF a.status<>'active' OR c.status<>'active' OR c.expires_on<current_date THEN RAISE EXCEPTION 'Compte ou carte bloqué(e) ou expiré(e)'; END IF;
 x:=(_data->>'amount')::numeric; n:=(_data->>'litres')::numeric; IF x IS NULL OR x<=0 OR n IS NULL OR n<=0 THEN RAISE EXCEPTION 'Montant et litres positifs requis'; END IF;
 sid:=(_data->>'station_id')::uuid; pid:=(_data->>'product_id')::uuid; vid:=NULLIF(_data->>'vehicle_id','')::uuid; did:=NULLIF(_data->>'driver_id','')::uuid; ref:=NULLIF(trim(_data->>'reference'),'');
 IF ref IS NULL OR NOT EXISTS(SELECT 1 FROM public.stations WHERE id=sid AND tenant_id=_tenant AND country_id=_country) OR NOT EXISTS(SELECT 1 FROM public.petroleum_products WHERE id=pid AND tenant_id=_tenant AND country_id=_country) THEN RAISE EXCEPTION 'Station, produit ou référence invalide'; END IF;
 IF c.vehicle_id IS NOT NULL AND c.vehicle_id IS DISTINCT FROM vid THEN RAISE EXCEPTION 'Véhicule non autorisé'; END IF;
 IF c.driver_id IS NOT NULL AND c.driver_id IS DISTINCT FROM did THEN RAISE EXCEPTION 'Conducteur non autorisé'; END IF;
 IF vid IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public.fuel_card_vehicles WHERE id=vid AND account_id=a.id AND active) THEN RAISE EXCEPTION 'Véhicule invalide'; END IF;
 IF did IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public.fuel_card_drivers WHERE id=did AND account_id=a.id AND active) THEN RAISE EXCEPTION 'Conducteur invalide'; END IF;
 j:=c.restrictions;
 IF j ? 'products' AND jsonb_array_length(j->'products')>0 AND NOT j->'products' ? pid::text THEN RAISE EXCEPTION 'Produit non autorisé'; END IF;
 IF j ? 'stations' AND jsonb_array_length(j->'stations')>0 AND NOT j->'stations' ? sid::text THEN RAISE EXCEPTION 'Station non autorisée'; END IF;
 IF j ? 'vehicles' AND jsonb_array_length(j->'vehicles')>0 AND (vid IS NULL OR NOT j->'vehicles' ? vid::text) THEN RAISE EXCEPTION 'Véhicule non autorisé'; END IF;
 IF j ? 'max_transaction' AND x>(j->>'max_transaction')::numeric THEN RAISE EXCEPTION 'Plafond transaction dépassé'; END IF;
 IF j ? 'max_litres' AND n>(j->>'max_litres')::numeric THEN RAISE EXCEPTION 'Volume transaction dépassé'; END IF;
 IF j ? 'start_hour' AND extract(hour FROM now())<(j->>'start_hour')::numeric OR j ? 'end_hour' AND extract(hour FROM now())>=(j->>'end_hour')::numeric THEN RAISE EXCEPTION 'Hors horaires autorisés (UTC)'; END IF;
 SELECT COALESCE(sum(amount),0) INTO day_total FROM public.fuel_card_transactions WHERE card_id=c.id AND kind='purchase' AND occurred_at>=date_trunc('day',now());
 SELECT COALESCE(sum(amount),0) INTO week_total FROM public.fuel_card_transactions WHERE card_id=c.id AND kind='purchase' AND occurred_at>=date_trunc('week',now());
 SELECT COALESCE(sum(amount),0) INTO month_total FROM public.fuel_card_transactions WHERE card_id=c.id AND kind='purchase' AND occurred_at>=date_trunc('month',now());
 IF j ? 'daily_amount' AND day_total+x>(j->>'daily_amount')::numeric OR j ? 'weekly_amount' AND week_total+x>(j->>'weekly_amount')::numeric OR j ? 'monthly_amount' AND month_total+x>(j->>'monthly_amount')::numeric THEN RAISE EXCEPTION 'Plafond périodique dépassé'; END IF;
 IF j ? 'daily_litres' AND n+COALESCE((SELECT sum(litres) FROM public.fuel_card_transactions WHERE card_id=c.id AND kind='purchase' AND occurred_at>=date_trunc('day',now())),0)>(j->>'daily_litres')::numeric OR j ? 'weekly_litres' AND n+COALESCE((SELECT sum(litres) FROM public.fuel_card_transactions WHERE card_id=c.id AND kind='purchase' AND occurred_at>=date_trunc('week',now())),0)>(j->>'weekly_litres')::numeric OR j ? 'monthly_litres' AND n+COALESCE((SELECT sum(litres) FROM public.fuel_card_transactions WHERE card_id=c.id AND kind='purchase' AND occurred_at>=date_trunc('month',now())),0)>(j->>'monthly_litres')::numeric THEN RAISE EXCEPTION 'Plafond litres dépassé'; END IF;
 IF c.allocated_limit>0 THEN IF x>c.remaining THEN RAISE EXCEPTION 'Allocation carte insuffisante'; END IF; ELSIF EXISTS(SELECT 1 FROM public.fuel_cards WHERE account_id=a.id AND allocated_limit>0) THEN RAISE EXCEPTION 'Allocation requise pour cette carte'; END IF;
 IF a.kind='prepaid' THEN IF a.prepaid_balance<x THEN RAISE EXCEPTION 'Solde principal insuffisant'; END IF; UPDATE public.fuel_card_accounts SET prepaid_balance=prepaid_balance-x WHERE id=a.id;
 ELSE IF a.credit_limit-a.credit_used<x THEN RAISE EXCEPTION 'Plafond principal dépassé'; END IF; UPDATE public.fuel_card_accounts SET credit_used=credit_used+x WHERE id=a.id; END IF;
 IF c.allocated_limit>0 THEN UPDATE public.fuel_cards SET remaining=remaining-x WHERE id=c.id; END IF;
 INSERT INTO public.fuel_card_transactions(tenant_id,country_id,account_id,card_id,station_id,product_id,vehicle_id,driver_id,kind,amount,litres,reference,actor_id) VALUES(_tenant,_country,a.id,c.id,sid,pid,vid,did,'purchase',x,n,ref,auth.uid()) RETURNING id INTO res;
 IF x>=COALESCE(NULLIF(j->>'alert_amount','')::numeric,100000) THEN INSERT INTO public.fuel_card_alerts(tenant_id,country_id,account_id,card_id,transaction_id,rule_code,explanation,severity) VALUES(_tenant,_country,a.id,c.id,res,'high_value','Transaction de montant élevé : '||x,'warning'); END IF;
 IF (SELECT count(*) FROM public.fuel_card_transactions WHERE card_id=c.id AND kind='purchase' AND occurred_at>now()-interval '10 minutes')>=3 THEN INSERT INTO public.fuel_card_alerts(tenant_id,country_id,account_id,card_id,transaction_id,rule_code,explanation,severity) VALUES(_tenant,_country,a.id,c.id,res,'rapid_repeat','Au moins 3 achats en 10 minutes','high'); END IF;
ELSIF _action='invoice' THEN
 IF a.kind<>'postpaid' OR (_data->>'period_end')::date<(_data->>'period_start')::date THEN RAISE EXCEPTION 'Période invalide'; END IF;
 IF EXISTS(SELECT 1 FROM public.fuel_card_invoices WHERE account_id=a.id AND period_start<=(_data->>'period_end')::date AND period_end>=(_data->>'period_start')::date) THEN RAISE EXCEPTION 'Période déjà facturée'; END IF;
 SELECT COALESCE(sum(t.amount),0) INTO x FROM public.fuel_card_transactions t WHERE t.account_id=a.id AND t.kind='purchase' AND t.occurred_at::date BETWEEN (_data->>'period_start')::date AND (_data->>'period_end')::date;
 IF x<=0 THEN RAISE EXCEPTION 'Aucune consommation à facturer'; END IF;
 INSERT INTO public.fuel_card_invoices(tenant_id,country_id,account_id,period_start,period_end,number,amount,actor_id) VALUES(_tenant,_country,a.id,(_data->>'period_start')::date,(_data->>'period_end')::date,'FC-'||upper(substr(replace(gen_random_uuid()::text,'-',''),1,12)),x,auth.uid()) RETURNING id INTO res;
 INSERT INTO public.fuel_card_transactions(tenant_id,country_id,account_id,kind,amount,reference,actor_id) VALUES(_tenant,_country,a.id,'invoice',x,res::text,auth.uid());
ELSIF _action='invoice_payment' THEN
 SELECT * INTO inv FROM public.fuel_card_invoices WHERE id=(_data->>'invoice_id')::uuid AND account_id=a.id AND tenant_id=_tenant AND country_id=_country FOR UPDATE; IF NOT FOUND THEN RAISE EXCEPTION 'Facture introuvable'; END IF;
 x:=(_data->>'amount')::numeric; IF x IS NULL OR x<=0 OR inv.paid+x>inv.amount THEN RAISE EXCEPTION 'Paiement invalide'; END IF;
 UPDATE public.fuel_card_invoices SET paid=paid+x WHERE id=inv.id;
 INSERT INTO public.fuel_card_transactions(tenant_id,country_id,account_id,kind,amount,reference,actor_id) VALUES(_tenant,_country,a.id,'payment',x,inv.id::text,auth.uid()) RETURNING id INTO res;
 IF COALESCE(_data->>'restore','false')='true' THEN
 IF a.kind<>'postpaid' OR x>a.credit_used THEN RAISE EXCEPTION 'Reconstitution invalide'; END IF;
 UPDATE public.fuel_card_accounts SET credit_used=credit_used-x WHERE id=a.id;
 INSERT INTO public.fuel_card_limit_events(tenant_id,country_id,account_id,old_limit,new_limit,reason,actor_id) VALUES(_tenant,_country,a.id,a.credit_limit-a.credit_used,a.credit_limit-a.credit_used+x,'Paiement facture '||inv.number,auth.uid());
 END IF;
ELSE RAISE EXCEPTION 'Action inconnue'; END IF;
PERFORM public.log_audit_event('fuel_card_'||_action,'fuel_cards',CASE WHEN _card IS NOT NULL THEN 'fuel_cards' ELSE 'fuel_card_accounts' END,COALESCE(res,_card,_account)::text,_country,jsonb_build_object('account_id',_account,'card_id',_card,'action',_action,'amount',_data->'amount'),NULL);
RETURN jsonb_build_object('id',res,'ok',true);
END $$;
REVOKE ALL ON FUNCTION public.fuel_card_action(text,uuid,uuid,uuid,uuid,jsonb) FROM PUBLIC; GRANT EXECUTE ON FUNCTION public.fuel_card_action(text,uuid,uuid,uuid,uuid,jsonb) TO authenticated; GRANT EXECUTE ON FUNCTION public.fuel_card_action(text,uuid,uuid,uuid,uuid,jsonb) TO service_role;