import { useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { useScope } from "@/hooks/useScope";
import { usePermissions } from "@/hooks/usePermissions";
import { useLanguage } from "@/hooks/useLanguage";
import { usePlatformAdmin } from "@/hooks/usePlatformAdmin";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card, CardContent } from "@/components/ui/card";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { toast } from "sonner";
import type { Json } from "@/integrations/supabase/types";

type Action = "account"|"card"|"vehicle"|"driver"|"status"|"replace"|"topup"|"allocate"|"return"|"limit"|"restrictions"|"purchase"|"invoice"|"invoice_payment";
const actions: Record<Action,[string,string,string[]]> = {
 account:["Nouveau compte","New account",["client_id","kind","contract_reference","limit"]],card:["Nouvelle carte","New card",["number","holder","expires_on","vehicle_id","driver_id"]],vehicle:["Ajouter un véhicule","Add vehicle",["plate","description"]],driver:["Ajouter un conducteur","Add driver",["name","phone"]],status:["Bloquer / débloquer","Block / unblock",["status"]],replace:["Remplacer","Replace",["number","expires_on"]],topup:["Recharger","Top up",["amount","reason"]],allocate:["Allouer","Allocate",["amount","reason"]],return:["Restituer","Return",["amount","reason"]],limit:["Modifier plafond","Change limit",["amount","reason"]],restrictions:["Restrictions","Restrictions",["products","stations","vehicles","max_transaction","max_litres","daily_amount","weekly_amount","monthly_amount","daily_litres","weekly_litres","monthly_litres","start_hour","end_hour"]],purchase:["Transaction","Purchase",["station_id","product_id","vehicle_id","driver_id","amount","litres","reference"]],invoice:["Facturer","Invoice",["period_start","period_end"]],invoice_payment:["Régler facture","Pay invoice",["invoice_id","amount","restore"]]
};
const fieldNames:Record<string,[string,string]> = {client_id:["Client","Customer"],kind:["Type","Type"],contract_reference:["Contrat / bon de commande","Contract / purchase order"],limit:["Plafond principal","Main limit"],number:["Numéro carte","Card number"],holder:["Titulaire","Holder"],expires_on:["Expiration","Expiry"],vehicle_id:["Véhicule","Vehicle"],driver_id:["Conducteur","Driver"],plate:["Immatriculation","Plate"],description:["Description","Description"],name:["Nom","Name"],phone:["Téléphone","Phone"],status:["Statut","Status"],amount:["Montant","Amount"],reason:["Motif","Reason"],products:["Produits autorisés","Allowed products"],stations:["Stations autorisées","Allowed stations"],vehicles:["Véhicules autorisés","Allowed vehicles"],max_transaction:["Montant / transaction","Amount / transaction"],max_litres:["Litres / transaction","Litres / transaction"],daily_amount:["Montant / jour","Amount / day"],weekly_amount:["Montant / semaine","Amount / week"],monthly_amount:["Montant / mois","Amount / month"],daily_litres:["Litres / jour","Litres / day"],weekly_litres:["Litres / semaine","Litres / week"],monthly_litres:["Litres / mois","Litres / month"],start_hour:["Début (UTC)","Start (UTC)"],end_hour:["Fin (UTC)","End (UTC)"],station_id:["Station","Station"],product_id:["Produit","Product"],litres:["Litres","Litres"],reference:["Référence unique","Unique reference"],period_start:["Début de période","Period start"],period_end:["Fin de période","Period end"],invoice_id:["Facture","Invoice"],restore:["Reconstituer le plafond","Restore credit"]};
const numeric = new Set(["limit","amount","litres","max_transaction","max_litres","daily_amount","weekly_amount","monthly_amount","daily_litres","weekly_litres","monthly_litres","start_hour","end_hour"]);
const tr=(language:string,fr:string,en:string)=>language==="en"?en:fr;
export function FuelCardsModule(){
 const {tenantId,countryId,scopeQuery}=useScope(); const {can}=usePermissions();const {isPlatformAdmin}=usePlatformAdmin();const {language}=useLanguage();const cache=useQueryClient();
 const [dialog,setDialog]=useState<{action:Action;account?:string;card?:string}|null>(null); const [form,setForm]=useState<Record<string,string>>({});const [busy,setBusy]=useState(false);const [search,setSearch]=useState("");
 const allowed=(action:Action)=>isPlatformAdmin||can("fuel_cards",action==="account"||action==="purchase"?"create":action==="invoice"||action==="invoice_payment"?"validate":"edit");
 const query=useQuery({queryKey:["fuel-cards",tenantId,countryId],enabled:!!tenantId&&!!countryId,queryFn:async()=>{
  const [accounts,cards,vehicles,drivers,transactions,limits,invoices,alerts,clients,stations,products]=await Promise.all([
   scopeQuery(supabase.from("fuel_card_accounts").select("*")).limit(500),scopeQuery(supabase.from("fuel_cards").select("*")).limit(500),scopeQuery(supabase.from("fuel_card_vehicles").select("*")).limit(500),scopeQuery(supabase.from("fuel_card_drivers").select("*")).limit(500),scopeQuery(supabase.from("fuel_card_transactions").select("*")).order("occurred_at",{ascending:false}).limit(500),scopeQuery(supabase.from("fuel_card_limit_events").select("*")).order("created_at",{ascending:false}).limit(500),scopeQuery(supabase.from("fuel_card_invoices").select("*")).order("created_at",{ascending:false}).limit(500),scopeQuery(supabase.from("fuel_card_alerts").select("*")).order("created_at",{ascending:false}).limit(500),scopeQuery(supabase.from("clients").select("id,name")).limit(500),scopeQuery(supabase.from("stations").select("id,name")).limit(500),scopeQuery(supabase.from("petroleum_products").select("id,name")).limit(500)]);
  for(const r of [accounts,cards,vehicles,drivers,transactions,limits,invoices,alerts,clients,stations,products])if(r.error)throw r.error;
  return {accounts:accounts.data||[],cards:cards.data||[],vehicles:vehicles.data||[],drivers:drivers.data||[],transactions:transactions.data||[],limits:limits.data||[],invoices:invoices.data||[],alerts:alerts.data||[],clients:clients.data||[],stations:stations.data||[],products:products.data||[]};
 }});const data=query.data;
 const name=(id:string)=>{const a=data?.accounts.find(x=>x.id===id);return data?.clients.find(x=>x.id===a?.client_id)?.name||id.slice(0,8)};
 const open=(action:Action,account?:string,card?:string,defaults:Record<string,string>={})=>{setForm(defaults);setDialog({action,account,card})};
 const options=(key:string)=>{const candidates=key==="client_id"?data?.clients:key==="station_id"||key==="stations"?data?.stations:key==="product_id"||key==="products"?data?.products:key==="vehicle_id"||key==="vehicles"?data?.vehicles.filter(x=>x.account_id===dialog?.account):key==="driver_id"?data?.drivers.filter(x=>x.account_id===dialog?.account):key==="invoice_id"?data?.invoices.filter(x=>x.account_id===dialog?.account&&Number(x.paid)<Number(x.amount)):[];return (candidates||[]).map(x=>({id:x.id,label:"name" in x?String(x.name):"plate" in x?String(x.plate):"number" in x?String(x.number):x.id.slice(0,8)}))};
 const submit=async()=>{if(!dialog||!tenantId||!countryId||!allowed(dialog.action))return;const body:Record<string,Json>={};for(const key of actions[dialog.action][2]){const v=form[key];if(!v||v==="none")continue;if(["products","stations","vehicles"].includes(key))body[key]=v.split(",");else if(numeric.has(key))body[key]=Number(v);else body[key]=v;}
  if(dialog.action==="restrictions"){const j={...body};for(const key of ["products","stations","vehicles"])if(!j[key])j[key]=[];body.restrictions=j;}if(dialog.action==="invoice_payment")body.restore=form.restore==="true";
  setBusy(true);const {error}=await supabase.rpc("fuel_card_action",{_action:dialog.action,_tenant:tenantId,_country:countryId,_account:dialog.account||undefined,_card:dialog.card||undefined,_data:body});setBusy(false);if(error){toast.error(error.message);return;}toast.success(tr(language,"Opération enregistrée","Saved"));setDialog(null);cache.invalidateQueries({queryKey:["fuel-cards",tenantId,countryId]});};
 if(!countryId)return <p>{tr(language,"Sélectionnez un pays.","Select a country.")}</p>;
 const money=(v:number)=>new Intl.NumberFormat(language==="en"?"en-GB":"fr-FR",{maximumFractionDigits:2}).format(v);
 const filtered=data?.accounts.filter(a=>name(a.id).toLowerCase().includes(search.toLowerCase())||a.contract_reference?.toLowerCase().includes(search.toLowerCase()))||[];
 const button=(action:Action,account?:string,card?:string,defaults?:Record<string,string>)=>allowed(action)&&<Button key={action} size="sm" variant="outline" onClick={()=>open(action,account,card,defaults)}>{tr(language,actions[action][0],actions[action][1])}</Button>;
 return <div className="space-y-5"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-xl font-display font-semibold">Fuel Cards</h2><p className="text-sm text-muted-foreground">{tr(language,"Prépayé et postpayé · comptes, cartes et consommations","Prepaid and postpaid · accounts, cards and purchases")}</p></div>{button("account")}</div><Input className="max-w-xs" placeholder={tr(language,"Rechercher un client…","Search customer…")} value={search} onChange={e=>setSearch(e.target.value)}/>{query.isLoading&&<p>{tr(language,"Chargement…","Loading…")}</p>}{query.error&&<p role="alert" className="text-destructive">{query.error.message}</p>}
 <Tabs defaultValue="accounts"><TabsList className="flex flex-wrap h-auto">{[["accounts","Comptes","Accounts"],["cards","Cartes","Cards"],["transactions","Transactions","Transactions"],["invoices","Factures","Invoices"],["limits","Journal plafonds","Limit log"],["alerts","Alertes","Alerts"]].map(([key,fr,en])=><TabsTrigger value={key} key={key}>{tr(language,fr,en)}</TabsTrigger>)}</TabsList>
 <TabsContent value="accounts" className="space-y-3">{filtered.map(a=><Card key={a.id}><CardContent className="p-4 space-y-3"><div className="flex justify-between"><strong>{name(a.id)} · {a.kind}</strong><span>{a.status}</span></div><p className="text-sm text-muted-foreground">{a.contract_reference}</p><p className="text-sm">{tr(language,"Solde principal","Main balance")}: {money(Number(a.prepaid_balance))} · {tr(language,"Plafond","Limit")}: {money(Number(a.credit_limit))} · {tr(language,"Utilisé","Used")}: {money(Number(a.credit_used))}</p><div className="flex flex-wrap gap-2">{button("card",a.id)}{button("vehicle",a.id)}{button("driver",a.id)}{button(a.kind==="prepaid"?"topup":"limit",a.id)}{a.kind==="postpaid"&&button("invoice",a.id)}</div></CardContent></Card>)}{!filtered.length&&!query.isLoading&&<p className="py-8 text-muted-foreground">{tr(language,"Aucun compte dans ce pays.","No accounts in this country.")}</p>}</TabsContent>
 <TabsContent value="cards" className="space-y-3">{data?.cards.filter(c=>filtered.some(a=>a.id===c.account_id)).map(c=><Card key={c.id}><CardContent className="p-4 space-y-2"><strong>{c.card_number} · {name(c.account_id)}</strong><p className="text-sm text-muted-foreground">{c.status} · {tr(language,"Expire","Expires")} {c.expires_on} · {tr(language,"Allocation restante","Remaining allocation")} {money(Number(c.remaining))}</p><div className="flex flex-wrap gap-2">{button("purchase",c.account_id,c.id)}{button("allocate",c.account_id,c.id)}{button("return",c.account_id,c.id)}{button("restrictions",c.account_id,c.id)}{button("status",c.account_id,c.id)}{button("replace",c.account_id,c.id)}</div></CardContent></Card>)}</TabsContent>
 <TabsContent value="transactions">{data?.transactions.map(x=><div key={x.id} className="border-b border-border py-3 text-sm">{x.occurred_at.slice(0,16).replace("T"," ")} · {name(x.account_id)} · {x.kind} · {money(Number(x.amount))} {x.litres?`· ${x.litres} L`:""} · {x.reference||x.note}</div>)}</TabsContent>
 <TabsContent value="invoices">{data?.invoices.map(x=><div key={x.id} className="border-b border-border py-3 text-sm flex flex-wrap justify-between gap-2"><span>{x.number} · {name(x.account_id)} · {x.period_start} → {x.period_end} · {money(Number(x.paid))}/{money(Number(x.amount))}</span>{Number(x.paid)<Number(x.amount)&&button("invoice_payment",x.account_id,undefined,{invoice_id:x.id})}</div>)}</TabsContent>
 <TabsContent value="limits">{data?.limits.map(x=><div key={x.id} className="border-b border-border py-3 text-sm">{x.created_at.slice(0,16).replace("T"," ")} · {name(x.account_id)} · {money(Number(x.old_limit))} → {money(Number(x.new_limit))} · {x.reason}</div>)}</TabsContent>
 <TabsContent value="alerts">{data?.alerts.map(x=><div key={x.id} className="border-b border-border py-3 text-sm">{x.severity} · {name(x.account_id)} · {x.rule_code} · {x.explanation}</div>)}</TabsContent></Tabs>
 <Dialog open={!!dialog} onOpenChange={v=>{if(!v)setDialog(null)}}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-xl"><DialogHeader><DialogTitle>{dialog&&tr(language,actions[dialog.action][0],actions[dialog.action][1])}</DialogTitle></DialogHeader><div className="grid sm:grid-cols-2 gap-4">{dialog&&actions[dialog.action][2].map(key=><div key={key}><Label htmlFor={`fuel-${key}`}>{tr(language,...fieldNames[key])}</Label>{["kind","status","restore","client_id","station_id","product_id","vehicle_id","driver_id","invoice_id","products","stations","vehicles"].includes(key)?<Select value={form[key]||undefined} onValueChange={value=>setForm(p=>({...p,[key]:value}))}><SelectTrigger id={`fuel-${key}`}><SelectValue placeholder={tr(language,"Choisir…","Select…")}/></SelectTrigger><SelectContent>{["vehicle_id","driver_id","products","stations","vehicles"].includes(key)&&<SelectItem value="none">{tr(language,"Aucune restriction","No restriction")}</SelectItem>}{(key==="kind"?[{id:"prepaid",label:tr(language,"Prépayé","Prepaid")},{id:"postpaid",label:tr(language,"Postpayé","Postpaid")}]:key==="status"?[{id:"blocked",label:tr(language,"Bloquée","Blocked")},{id:"active",label:tr(language,"Active","Active")}]:key==="restore"?[{id:"false",label:tr(language,"Sans reconstitution","No restoration")},{id:"true",label:tr(language,"Reconstituer","Restore")}]:options(key)).map(o=><SelectItem key={o.id} value={o.id}>{o.label}</SelectItem>)}</SelectContent></Select>:<Input id={`fuel-${key}`} type={numeric.has(key)?"number":["expires_on","period_start","period_end"].includes(key)?"date":"text"} min={numeric.has(key)?0:undefined} step="any" value={form[key]||""} onChange={e=>setForm(p=>({...p,[key]:e.target.value}))}/>}</div>)}</div><div className="flex justify-end gap-2"><Button variant="outline" onClick={()=>setDialog(null)}>{tr(language,"Annuler","Cancel")}</Button><Button disabled={busy} onClick={submit}>{tr(language,"Enregistrer","Save")}</Button></div></DialogContent></Dialog></div>;
}
