// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-stations.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/_supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.90.1";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}

// src/lib/mcp/tools/list-stations.ts
var list_stations_default = defineTool({
  name: "list_stations",
  title: "List stations",
  description: "List all service stations in the network with name and location.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await supabaseForUser(ctx).from("stations").select("id, name, location, zone_id, created_at").order("name");
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { stations: data }
    };
  }
});

// src/lib/mcp/tools/list-clients.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var list_clients_default = defineTool2({
  name: "list_clients",
  title: "List clients",
  description: "List customer accounts (clients). Optionally filter to active clients only.",
  inputSchema: {
    active_only: z.boolean().optional().describe("When true, only return active clients.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ active_only }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let query = supabaseForUser(ctx).from("clients").select("id, name, contact_name, email, phone, address, tax_id, is_active").order("name");
    if (active_only) query = query.eq("is_active", true);
    const { data, error } = await query;
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { clients: data }
    };
  }
});

// src/lib/mcp/tools/list-suppliers.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
var list_suppliers_default = defineTool3({
  name: "list_suppliers",
  title: "List suppliers",
  description: "List fuel suppliers (fournisseurs). Optionally filter to active suppliers only.",
  inputSchema: {
    active_only: z2.boolean().optional().describe("When true, only return active suppliers.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ active_only }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let query = supabaseForUser(ctx).from("suppliers").select("id, name, contact_name, email, phone, product_type, tax_id, is_active").order("name");
    if (active_only) query = query.eq("is_active", true);
    const { data, error } = await query;
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { suppliers: data }
    };
  }
});

// src/lib/mcp/tools/list-price-structures.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_price_structures_default = defineTool4({
  name: "list_price_structures",
  title: "List price structures",
  description: "List fuel price structures by effective period, including Super and Gasoil selling prices.",
  inputSchema: {
    country: z3.string().optional().describe("Filter by country code/name (e.g. Benin).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ country }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let query = supabaseForUser(ctx).from("price_structures").select("id, country, effective_date, label, super_price, gasoil_price, is_active").order("effective_date", { ascending: false });
    if (country) query = query.eq("country", country);
    const { data, error } = await query;
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { price_structures: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "zpnnwiddxjotndguhqsc";
var mcp_default = defineMcp({
  name: "yatt-energy-mcp",
  title: "YATT & CO ENERGY MCP",
  version: "0.1.0",
  instructions: "Tools for the YATT & CO ENERGY station management app (Benin). Read stations, clients, suppliers, and fuel price structures for the signed-in user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_stations_default, list_clients_default, list_suppliers_default, list_price_structures_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
